apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Add your IAM role configurations here
    # Example:
    # - rolearn: arn:aws:iam::123456789012:role/YourEKSNodeInstanceRole
    #   username: your-node
    #   groups:
    #     - system:bootstrappers
    #     - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::373894711056:user/admin
      username: admin
      groups:
        - system:masters
